### ISSUE TITLE
Cant change the size of the card

### ISSUE THREAD

**Issue by bananflugan** [custom-cards/circle-sensor-card#23]
Hi,

I am having issues changing the size of this great custom card.

No matter what i put under the style section nothing is happening to the card, it stays very big.
The config i currently have in my ui config is the following:

`type: custom:circle-sensor-card
        name: Humidity 1st Floor
        entity: sensor.humidity_3
        min: 0
        max: 100
        gradient: true
        stroke_width: 7
        font_style:
          color: black
          font-size: 1.5em
        style:
          width: 45px
          hight: 45px`

Best regards
bananflugan

**Comment by marktillo** [comment]
You’ve spelt height wrong also you may have to use style:
  Ha-card{ 
    width:  50px !important;
    Height:50px !important;
    }

**Comment by a-bianucci** [comment]
I have the same issue

```
type: 'custom:circle-sensor-card'
entity: sensor.temperature_measurement
name: Living Room Temp
stroke_width: 10
gradient: true
units: F
fill: 'rgba(99,94,93,.95)'
font_style:
  color: white
  font-size: 2em
  font-family: Avantgarde
color_stops:
  '65': '#639BD5'
  '70': '#33931B'
  '75': '#BD371C'
style:
  width: 25px
  height: 25px

```
