### ISSUE TITLE
Bug in version 1.2.1

### ISSUE THREAD

**Issue by therealhalifax** [custom-cards/circle-sensor-card#28]
since the update to version 1.2.1 i see a very strange behavior. the size and the position of the circles is changed. Please see the attached pictures: [https://www.dropbox.com/sh/xcnpjcrahft9lcd/AAB01Mg_c4_w5hBmMqjig72Ca?dl=0](url)
```

  - type: custom:circle-sensor-card
    entity: sensor.synologynas_volume_1_volume_used
    max: 100
    min: 0
    stroke_width: 20
    fill: rgba(0, 0, 0, 0)
    font_style:
      color: white
      font-size: 90%
    gradient: false
    units: '%'
    show_max: false
    color_stops:
      '80': '#FFFF00'
      '90': '#FF0000'
    style:
      top: 25%
      left: 8%
      width: 10%
      transform: none
```
