### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by giros79** [custom-cards/circle-sensor-card#39]
Hi everybody. I tried to add this card but seems something is wrong. 
Added as resource (module) but when create a manual card copying script (with a correct sensor) it doesn't work. 
"No card type configurated"

Thanks for helping me

**Comment by Pihlflykt** [comment]
Same here... doesn't work for me.

**Comment by DJBenson** [comment]
There's a bug - try adding the following to your configuration, just beneath your entity definition;
```
style:
  width: 100%
  height: 100%
  left: 0
  top: 0
```
